### ISSUE TITLE
Debate: Should we replace the Logo's PNG based on the new SVG?

### ISSUE THREAD

**Issue by x-N0** [bitcartcc/bitcart-media#4]
https://github.com/bitcartcc/bitcart-media/blob/master/logo.png
For a new PNG to make sure that the issues of the older logo are gone.

**Comment by MrNaif2018** [comment]
Yes, we should use svg's everywhere instead

**Comment by MrNaif2018** [comment]
logo.png is now an exported version of logo.svg
